import { AssParseResult, WrapStyle } from "../src/ts/index"

export interface TestFile {
	result: AssParseResult
	file: string
}

export const sampleFiles: TestFile[] = [
	{
		result: {
			warnings: [],
			error: false,
			result: {
				script_info: {
					title: "Default Aegisub file",
					original_script: "<unknown>",
					original_translation: "",
					original_editing: "",
					original_timing: "",
					synch_point: "",
					script_updated_by: "",
					update_details: "",
					script_type: "V4Plus",
					collisions: "",
					play_res_y: 0,
					play_res_x: 0,
					play_depth: "",
					timer: "",
					wrap_style: 0,
					scaled_border_and_shadow: true,
					video_aspect_ratio: 0,
					video_zoom: 0,
					ycbcr_matrix: "None",
				},
				styles: [
					{
						name: "Default",
						fontname: "Disney Simple",
						fontsize: 60,
						primary_colour: { r: 255, g: 255, b: 255, a: 0 },
						secondary_colour: { r: 255, g: 0, b: 0, a: 0 },
						outline_colour: { r: 142, g: 142, b: 142, a: 0 },
						back_colour: { r: 0, g: 0, b: 0, a: 0 },
						bold: true,
						italic: false,
						underline: false,
						strike_out: false,
						scale_x: 100,
						scale_y: 100,
						spacing: 0.3,
						angle: 232,
						border_style: 3,
						outline: 3.6,
						shadow: 0.7,
						alignment: 5,
						margin_l: 20,
						margin_r: 20,
						margin_v: 6,
						encoding: 1,
					},
					{
						name: "Style 2",
						fontname: "Disney Simple",
						fontsize: 60,
						primary_colour: { r: 255, g: 255, b: 255, a: 0 },
						secondary_colour: { r: 45, g: 0, b: 255, a: 0 },
						outline_colour: { r: 142, g: 142, b: 142, a: 0 },
						back_colour: { r: 0, g: 0, b: 0, a: 0 },
						bold: true,
						italic: false,
						underline: false,
						strike_out: false,
						scale_x: 100,
						scale_y: 100,
						spacing: 0,
						angle: 0,
						border_style: 1,
						outline: 3,
						shadow: 0,
						alignment: 5,
						margin_l: 20,
						margin_r: 20,
						margin_v: 6,
						encoding: 1,
					},
					{
						name: "Style with ; xD",
						fontname: "Disney Simple",
						fontsize: 60,
						primary_colour: { r: 255, g: 255, b: 255, a: 0 },
						secondary_colour: { r: 45, g: 0, b: 255, a: 239 },
						outline_colour: { r: 142, g: 142, b: 142, a: 0 },
						back_colour: { r: 0, g: 0, b: 0, a: 0 },
						bold: false,
						italic: true,
						underline: true,
						strike_out: true,
						scale_x: 1200,
						scale_y: 1010,
						spacing: 12.5,
						angle: 2,
						border_style: 1,
						outline: 1,
						shadow: 1,
						alignment: 9,
						margin_l: 20,
						margin_r: 20,
						margin_v: 6,
						encoding: 1,
					},
				],
				events: [
					{
						type: "Dialogue",
						layer: 0,
						start: { hour: 0, min: 0, sec: 0, hundred: 0 },
						end: { hour: 0, min: 0, sec: 5, hundred: 0 },
						style: "Default",
						name: "",
						margin_l: 0,
						margin_r: 0,
						margin_v: 0,
						effect: "",
						text: "Hello 1",
					},
					{
						type: "Comment",
						layer: 0,
						start: { hour: 0, min: 0, sec: 5, hundred: 0 },
						end: { hour: 0, min: 0, sec: 8, hundred: 0 },
						style: "Default",
						name: "",
						margin_l: 0,
						margin_r: 0,
						margin_v: 0,
						effect: "",
						text: "Hello Comment",
					},
					{
						type: "Dialogue",
						layer: 0,
						start: { hour: 0, min: 0, sec: 8, hundred: 0 },
						end: { hour: 0, min: 0, sec: 11, hundred: 0 },
						style: "Style with ; xD",
						name: "",
						margin_l: 0,
						margin_r: 0,
						margin_v: 0,
						effect: "",
						text: "Text with, xD",
					},
				],
				extra_sections: {
					"Aegisub Project Garbage": {
						"Last Style Storage": "Default",
					},
				},
				file_props: { line_type: "Lf", file_type: "UTF-8" },
			},
		},
		file: "test.ass",
	},
]
